title: seektruth_one
url: https://www.seektruth.one
basreurl: ""
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

github:
    is_project_page: false

title: seektruth_one
description: A free and honest inquiry into what is real.
