title: seek(truth₁)
url: https://www.seektruth.one
baseurl: ""
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

github:
    is_project_page: false

title: seek(truth₁)
description: A free and honest inquiry into the real.

media: https://github.com/jemajoign/seektruth_one/raw/refs/heads/main/media/